Ka/registrar fix (#243)
Changes to support gcc 9.3.0 build (Dunfell)

* flutter_desktop_texture_registrar: fix build error for unordered_map

With using a old version gcc (9.3.0), the following error happens.

```
shell/platform/homescreen/./flutter_desktop_texture_registrar.h:31:8: error: no template named 'unordered_map' in namespace 'std'
  std::unordered_map<int64_t, std::unique_ptr<GL_TEXTURE_2D_DESC>>
  ~~~~~^
```

So, I added `#include <unordered_map>` to fix the error.

Signed-off-by: Kazuyoshi Akiyama <kazuyoshi.akiyama@woven-planet.global>

* package_info: fix the error of missing logging.h

I faced with the following error.

```
plugins/package_info/package_info.cc:21:10: fatal error: 'logging.h' file not found
         ^~~~~~~~~~~
```

So, I changed "logging.h" to <plugins/common/common.h>

Signed-off-by: Kazuyoshi Akiyama <kazuyoshi.akiyama@woven-planet.global>

* time_tools: fix build error of the missing header

The following error happens.

```
plugins/common/time/time_tools.cc:26:29: error: no member named 'chrono' in namespace 'std'
  const auto seconds = std::chrono::duration_cast<std::chrono::seconds>(epoch);
                       ~~~~~^
```

So, I added `#include <chrono>` to fix the error.

Signed-off-by: Kazuyoshi Akiyama <kazuyoshi.akiyama@woven-planet.global>

* flutter_desktop_texture_registrar: fix build error of the missing header

Error:

```
shell/platform/homescreen/./flutter_desktop_texture_registrar.h:30:8: error: no type named 'mutex' in namespace 'std'
  std::mutex texture_mutex;
  ~~~~~^
```

CounterMeasure:

- add `#include <mutex>`

Signed-off-by: Kazuyoshi Akiyama <kazuyoshi.akiyama@woven-planet.global>

* window: fix build error of no viable conversion

Error:

```
shell/wayland/window.cc:236:36: error: no viable conversion from 'std::shared_ptr<Engine>' to 'Engine *'
  w->m_backend->Resize(w->m_index, w->m_flutter_engine, w->m_geometry.width,
                                   ^~~~~~~~~~~~~~~~~~~
```

CounterMeasure:

- Use get() of std::shared_ptr when passing Engine to Resize()

Signed-off-by: Kazuyoshi Akiyama <kazuyoshi.akiyama@woven-planet.global>

* display: fix build error of the undeclared identifier

Error:

```
shell/wayland/display.cc:121:5: error: use of undeclared identifier 'xdg_wm_base_destroy'
    xdg_wm_base_destroy(m_xdg_wm_base);
    ^
shell/wayland/display.cc:142:3: error: use of undeclared identifier 'xdg_wm_base_pong'
  xdg_wm_base_pong(xdg_wm_base, serial);
  ^
shell/wayland/display.cc:145:46: error: constexpr variable cannot have non-literal type 'const struct xdg_wm_base_listener'
static constexpr struct xdg_wm_base_listener xdg_wm_base_listener = {
                                             ^
```

CounterMeasure:

- Add the section of `if defined(ENABLE_XDG_CLIENT)` to the above

Signed-off-by: Kazuyoshi Akiyama <kazuyoshi.akiyama@woven-planet.global>

Signed-off-by: Kazuyoshi Akiyama <kazuyoshi.akiyama@woven-planet.global>